# Generated by Django 5.1.6 on 2025-05-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('school', 'Maktab'), ('kindergarten', "Bog'cha"), ('hospital', 'Shifoxona')], max_length=50)),
                ('maintenance_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.district')),
            ],
        ),
    ]
