# Generated by Django 5.1.6 on 2025-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_viloyat_district_viloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='maintenance_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
