# Generated by Django 5.1.6 on 2025-05-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_expensebreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tuman nomi'),
        ),
        migrations.AlterField(
            model_name='district',
            name='viloyat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.viloyat', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='expensebreakdown',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Xarajat summasi'),
        ),
        migrations.AlterField(
            model_name='expensebreakdown',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Xarajat kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='expensebreakdown',
            name='maintenance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='institutions.maintenancerecord', verbose_name="Ta'mirlash tarixi"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('school', 'Maktab'), ('kindergarten', "Bog'cha"), ('hospital', 'Shifoxona')], max_length=50, verbose_name='Muassasa turi'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='maintenance_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Umumiy ta'mirlash budjeti"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='maintenance_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name="Ta'mirlash sababi"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Muassasa nomi'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ajratilgan summa'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='institutions.institution', verbose_name='Muassasa'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='reason',
            field=models.CharField(max_length=255, verbose_name="Ta'mirlash sababi"),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='viloyat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Viloyat nomi'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Pasport raqami')),
                ('description', models.TextField(verbose_name='Shikoyat matni')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/', verbose_name='Ilova (foto, hujjat)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='institutions.institution', verbose_name='Muassasa')),
            ],
        ),
    ]
