# Generated by Django 5.1.6 on 2025-05-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_district_name_alter_district_viloyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='free_medications_list',
            field=models.TextField(blank=True, null=True, verbose_name="Bepul dorilar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='maintenance_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Umumiy ta'mirlash budjeti"),
        ),
    ]
