# Generated by Django 5.1.6 on 2025-05-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_institution_free_medications_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ree_medications_list',
            field=models.TextField(blank=True, verbose_name="Bepul dori vositalari ro'yxati"),
        ),
    ]
