# Generated by Django 5.1.6 on 2025-05-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_institution_ree_medications_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='ree_medications_list',
        ),
        migrations.AlterField(
            model_name='institution',
            name='free_medications_list',
            field=models.TextField(blank=True, default='', verbose_name="Bepul dori vositalari ro'yxati"),
            preserve_default=False,
        ),
    ]
