# Generated by Django 5.1.6 on 2025-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_remove_institution_ree_medications_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='free_medications_list',
        ),
        migrations.AddField(
            model_name='institution',
            name='ree_medications_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
