# Generated by Django 5.1.6 on 2025-05-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_remove_institution_free_medications_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (ixtiyoriy)")),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_medications', to='institutions.institution', verbose_name='Muassasa')),
            ],
        ),
    ]
